In [94]:
import polars as pl
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [95]:
df = pl.read_csv('data_neural_network.csv')
#df

In [96]:
# Excluir a coluna density que não está normalizada
df = df.drop('density')
# Conversão de strings para números
#mapper = {
#    'Photon':-1,
#    'Proton':float(np.log(1)),
#    'Iron':float(np.log(56))
#}

mapper = {
    'Photon':0,
    'Proton':1,
    'Iron':2
}

trigs = []
for i in range(1,101):
    trig = 'TRIG' + str(i)
    trigs.append(trig)

trigs = dict((list(enumerate(trigs, 1))))

trigs = {value: key for key, value in trigs.items()}

df = df.with_columns(
    pl.col('composition').map_dict(mapper, default=None),
    pl.col('TRIG').map_dict(trigs, default=None)
    )

In [97]:
df

shape: (2_000, 4)
┌──────┬─────────────┬───────────┬────────────────────┐
│ TRIG ┆ composition ┆ energy    ┆ density_normalized │
│ ---  ┆ ---         ┆ ---       ┆ ---                │
│ i64  ┆ i64         ┆ f64       ┆ f64                │
╞══════╪═════════════╪═══════════╪════════════════════╡
│ 65   ┆ 0           ┆ 1.0000e14 ┆ 0.001325           │
│ 29   ┆ 1           ┆ 2.1500e15 ┆ 0.014233           │
│ 54   ┆ 2           ┆ 4.6400e15 ┆ 0.076239           │
│ 27   ┆ 2           ┆ 1.0000e14 ┆ 0.000189           │
│ …    ┆ …           ┆ …         ┆ …                  │
│ 27   ┆ 1           ┆ 4.6400e15 ┆ 0.084529           │
│ 2    ┆ 1           ┆ 2.1500e14 ┆ 0.000568           │
│ 11   ┆ 1           ┆ 4.6400e14 ┆ 0.000946           │
│ 90   ┆ 1           ┆ 2.1500e15 ┆ 0.008214           │
└──────┴─────────────┴───────────┴────────────────────┘

In [98]:
df_filtered = df.filter(pl.col("TRIG") == 24)
df_filtered

shape: (20, 4)
┌──────┬─────────────┬───────────┬────────────────────┐
│ TRIG ┆ composition ┆ energy    ┆ density_normalized │
│ ---  ┆ ---         ┆ ---       ┆ ---                │
│ i64  ┆ i64         ┆ f64       ┆ f64                │
╞══════╪═════════════╪═══════════╪════════════════════╡
│ 24   ┆ 2           ┆ 2.1500e14 ┆ 0.000303           │
│ 24   ┆ 0           ┆ 4.6400e14 ┆ 0.004845           │
│ 24   ┆ 0           ┆ 1.0000e13 ┆ 0.0                │
│ 24   ┆ 1           ┆ 1.0000e14 ┆ 0.00053            │
│ …    ┆ …           ┆ …         ┆ …                  │
│ 24   ┆ 1           ┆ 1.0000e15 ┆ 0.015445           │
│ 24   ┆ 0           ┆ 1.0000e14 ┆ 0.000379           │
│ 24   ┆ 1           ┆ 1.0000e13 ┆ 0.000151           │
│ 24   ┆ 1           ┆ 2.1500e15 ┆ 0.033615           │
└──────┴─────────────┴───────────┴────────────────────┘

In [99]:
df_neural = df.group_by('TRIG').agg(pl.col("density_normalized","composition", "energy"))
df_neural = df_neural.with_columns(pl.col('TRIG').cast(pl.Utf8))
df_neural = df_neural.transpose(column_names= 'TRIG')

In [100]:
df_neural

shape: (3, 100)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ 72        ┆ 64        ┆ 40        ┆ 96        ┆ … ┆ 15        ┆ 55        ┆ 95        ┆ 63       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ list[f64] ┆ list[f64] ┆ list[f64] ┆ list[f64] ┆   ┆ list[f64] ┆ list[f64] ┆ list[f64] ┆ list[f64 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ [0.000076 ┆ [0.002877 ┆ [0.000114 ┆ [0.006435 ┆ … ┆ [0.00988, ┆ [0.314873 ┆ [0.001893 ┆ [0.03403 │
│ ,         ┆ ,         ┆ ,         ┆ ,         ┆   ┆ 0.001136, ┆ ,         ┆ ,         ┆ 1, 0.011 │
│ 0.000303, ┆ 0.000038, ┆ 0.015975, ┆ 0.00053,  ┆   ┆ …         ┆ 0.032063, ┆ 0.005792, ┆ 848, …   │
│ …         ┆ …         ┆ …         ┆ …         ┆   ┆ 0.000568] ┆ …         ┆ …         ┆ 0.014839 │
│ 0.001628] ┆ 0.025287] ┆ 0.000719] ┆ 0.035242] ┆   ┆           ┆ 0.184465] ┆ 0.000454] ┆ ]        │
│ [2.0,     ┆ [1.0,     ┆ [0.0,     ┆ [0.0,     ┆ … ┆ [1.0,     ┆ [0.0,     ┆ [1.0,     ┆ [1.0,    │
│ 1.0, …    ┆ 0.0, …    ┆ 0.0, …    ┆ 2.0, …    ┆   ┆ 0.0, …    ┆ 0.0, …    ┆ 1.0, …    ┆ 2.0, …   │
│ 2.0]      ┆ 1.0]      ┆ 0.0]      ┆ 1.0]      ┆   ┆ 2.0]      ┆ 2.0]      ┆ 1.0]      ┆ 0.0]     │
│ [2.1500e1 ┆ [2.1500e1 ┆ [1.0000e1 ┆ [1.0000e1 ┆ … ┆ [1.0000e1 ┆ [2.1500e1 ┆ [4.6400e1 ┆ [2.1500e │
│ 4, 1.0000 ┆ 4, 1.0000 ┆ 4, 2.1500 ┆ 5, 4.6400 ┆   ┆ 5, 2.1500 ┆ 5, 4.6400 ┆ 4, 1.0000 ┆ 15, 2.15 │
│ e14, …    ┆ e13, …    ┆ e15, …    ┆ e14, …    ┆   ┆ e14, …    ┆ e14, …    ┆ e15, …    ┆ 00e15, … │
│ 1.0000e…  ┆ 1.0000e…  ┆ 2.1500e…  ┆ 4.6400e…  ┆   ┆ 2.1500e…  ┆ 4.6400e…  ┆ 1.0000e…  ┆ 1.0000e… │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [101]:
# Se eu quiser mostrar qual tanque a lista se refere, devo usar o parâmetro named = True
#density = df_neural.row(0, named= True)
density = df_neural.row(0)
composition = df_neural.row(1)
energy = df_neural.row(2)

In [102]:
len(density)

100

In [103]:
# Separação dos dados de teste e treino

from sklearn.model_selection import train_test_split

# Separação dos dados mas mantendo a dimensão
def custom_train_test_split(X, y, test_size=0.2):
    X_train, X_test, y_train, y_test = [], [], [], []

    for i in range(len(X)):
        # Realiza o split para cada lista interna
        X_tr, X_te, y_tr, y_te = train_test_split(X[i], y[i], test_size=test_size)
        
        # Adiciona os resultados nas listas
        X_train.append(X_tr)
        X_test.append(X_te)
        y_train.append(y_tr)
        y_test.append(y_te)
    
    return X_train, X_test, y_train, y_test

# Realiza a separação
X_train, X_test, Y_train, Y_test = custom_train_test_split(density, composition, test_size=0.2)

# Converte as listas para numpy arrays
X_train = np.array(X_train).T
X_test = np.array(X_test).T
Y_test = np.array(Y_test).T
Y_train = np.array(Y_train,dtype = int).T

Y_train_flat = np.array([item for sublist in Y_train for item in sublist])
num_classes = 3  

# Converte para one-hot encoding
Y_train_one_hot = np.eye(num_classes)[Y_train_flat]
Y_train_one_hot = Y_train_one_hot.reshape(100, 16, num_classes)
#Y_train_one_hot = Y_train_one_hot.reshape(-1, num_classes)

In [105]:
def one_hot_encode_and_flatten(y, num_classes=3):
    # Cria um array de zeros com forma (samples, tanques, classes)
    y_one_hot = np.eye(num_classes)[y]
    # Achata para (samples, tanques * classes)
    return y_one_hot.reshape(y.shape[0], -1)

# Converter para one-hot e achatar
Y_train_encoded = one_hot_encode_and_flatten(Y_train)

# Y_train_encoded agora tem a forma (16, 300)
print(Y_train_encoded.shape)

(16, 300)

In [ ]:
Y_train_one_hot

array([[[0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        ...,
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 1., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        ...,
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]],

       [[0., 0., 1.],
        [0., 0., 1.],
        [1., 0., 0.],
        ...,
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       ...,

       [[1., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        ...,
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        ...,
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]],

       [[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        ...,
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]]])

In [ ]:
Y_train_one_hot.shape

(100, 16, 3)

Vamos usar a arquitetura Feed-Forward Network pois teremos camadas sucessivas que alimentam as próximas - começando na camada de entrada e terminando na camada de saída. Todos os nós da rede estão conectados aos da próxima camada. 

Para um vetor *z* de dimensão *K* classes, temos que a função softmax é definida como
$$softmax(z_i) = \frac{exp(z_i)}{\sum_{j = 1}^{K} exp(z_j)}, 1 \leq i \leq K$$ 

Ainda, temos que o vetor *z* é definido por

$$z = \left(\sum_{i = 1}^{n}w_ix_i\right) + b $$

onde, $x_i$ são as entradas, $w_i$ são os pesos e *b* é o bias (viés). Sendo assim, a função softmax transforma o vetor *z* em probabilidades entre 0 e 1.

Para treinar o modelo, vamos utilizar a **Função de perda de Entropia Cruzada (Cross-Entropy Loss)**. A distância entre a saída do modelo e a saída real é chamada de função de perda ou de custo. E portanto, temos que minimizar essa distância, ou seja, essa perda, ao máximo para que o modelo tenha resultados melhores. Na forma matemática, estaremos calculando os pesos $w_i$ e o bias *b* com a função de perda e depois otimizando esses valores minimizandos-os com o **Gradiente Descendente Estocástico.**

In [ ]:
# Arquitetura que será usada: feed-forward network
# Qual será o tamanho da rede neural? Digo, tamanho de cada camada. 
# Quais pesos vou inicializar?
# Qual função de ativação vou usar? Deve ser não linear Softmax
# Como minimizar os pesos? Função de Perda deve ser diferenciável, isso implica que a função de ativação também deve ser diferenciável.
# Gradiente descendente
# Backpropagation

In [ ]:
class NeuralNetwork:
    def __init__(self, n_inputs, n_neurons):
    # Inicialização dos pesos e bias
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
    # Calcula os valores de saída de cada camada
        self.inputs = inputs
        self.output = np.dot(inputs, self.weights) + self.biases # X.W + b

    def backward(self, dvalues):
        # Gradiente dos parâmetros
        self.dweights = np.dot(self.inputs.T, dvalues)
        self.dbiases = np.sum(dvalues, axis = 0, keepdims = True)
        # Gradiente dos valores
        self.dinputs = np.dot(dvalues, self.weights.T)

In [ ]:
class ReLU():
    def forward(self, inputs):
        self.inputs = inputs
        self.output = np.maximum(0, inputs) # Função ReLU R(x) = max(0,x)
    def backward(self,dvalues):
        self.dinputs = dvalues.copy()
        self.dinputs[self.inputs <= 0] = 0

In [ ]:
class Softmax():
    def forward(self,inputs):
        # Probabilidades não normalizadas
        exp_values = np.exp(inputs - np.max(inputs, axis = 1, keepdims = True))
        # Normalização
        probabilities = exp_values / np.sum(exp_values, axis = 1, keepdims = True)
        self.output = probabilities

In [ ]:
class Loss:
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss

In [ ]:
class LossCategoricalCrossentropy(Loss):
    # Forward pass
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)

        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[
                range(samples),
                y_true
            ]

        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(
                y_pred_clipped * y_true,
                axis=1
            )
        else:
            raise ValueError("Formato de y_true não suportado.")
        
        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods


    def backward(self, dvalues, y_true):

        samples = len(dvalues)
        labels = len(dvalues[0])

        if len(y_true.shape) == 1:
            y_true = np.eye(labels)[y_true]

        # Gradiente
        self.dinputs = -y_true / dvalues
        # Normalização
        self.dinputs = self.dinputs / samples

In [ ]:
class Activation_Softmax_Loss_CategoricalCrossentropy:
    
    def __init__(self):
        self.activation = Softmax()
        self.loss = LossCategoricalCrossentropy()

    def forward(self, inputs, y_true):
        self.activation.forward(inputs)
        self.output = self.activation.output
        return self.loss.calculate(self.output, y_true)

    def backward(self, dvalues, y_true):
        samples = len(dvalues)

        if len(y_true.shape) == 2:
            y_true = np.argmax(y_true, axis=1)

        self.dinputs = dvalues.copy()
        # Gradiente
        self.dinputs[range(samples), y_true] -= 1
        # Normalização
        self.dinputs = self.dinputs / samples

In [ ]:
# Gradiente Descendente 
class Optimizer_GD:
 
 def __init__(self, learning_rate=0.01):
  self.learning_rate = learning_rate

 def update_params(self, layer):
  layer.weights += -self.learning_rate * layer.dweights
  layer.biases += -self.learning_rate * layer.dbiases

In [107]:
# Cria a primeira camada
layer1 = NeuralNetwork(100, 64)

# Cria a função de ativação ReLU
activation1 = ReLU()

# Cria uma segunda camada
layer2 = NeuralNetwork(64, 300)

# Cria a função perda e softmax
loss_activation = Activation_Softmax_Loss_CategoricalCrossentropy()

# Cria o gradiente descendente
optimizer = Optimizer_GD()

# Treinamento em loop
for epoch in range(10000):
    # Com os dados de treino, aplicando o método forward
    layer1.forward(X_train)
    
    # Usa a função de ativação da saída da primeira camada
    activation1.forward(layer1.output)
    
    # Passe os resultados para a próxima camada
    layer2.forward(activation1.output)
    
    # Usa os dados da segunda camada para a função de perda e softmax
    loss = loss_activation.forward(layer2.output, Y_train_encoded)
    
    # Calcula a precisão
    predictions = np.argmax(loss_activation.output, axis=1)
    if len(Y_train_encoded.shape) == 2:
        Y_train_encoded = np.argmax(Y_train_encoded, axis=1)
    accuracy = np.mean(predictions == Y_train_encoded)
    
    if not epoch % 100:
        print(f'epoch: {epoch}, ' +
              f'acc: {accuracy:.3f}, ' +
              f'loss: {loss:.3f}')
    
    # Backward
    loss_activation.backward(loss_activation.output, Y_train_encoded)
    layer2.backward(loss_activation.dinputs)
    activation1.backward(layer2.dinputs)
    layer1.backward(activation1.dinputs)
    
    # Atualiza o peso e bias para as camadas 1 e 2
    optimizer.update_params(layer1)
    optimizer.update_params(layer2)

epoch: 0, acc: 0.000, loss: 5.704
epoch: 100, acc: 0.375, loss: 5.371
epoch: 200, acc: 0.375, loss: 5.039
epoch: 300, acc: 0.375, loss: 4.702
epoch: 400, acc: 0.375, loss: 4.345
epoch: 500, acc: 0.375, loss: 3.915
epoch: 600, acc: 0.375, loss: 3.274
epoch: 700, acc: 0.375, loss: 2.283
epoch: 800, acc: 0.375, loss: 1.514
epoch: 900, acc: 0.375, loss: 1.265
epoch: 1000, acc: 0.375, loss: 1.186
epoch: 1100, acc: 0.375, loss: 1.152
epoch: 1200, acc: 0.375, loss: 1.134
epoch: 1300, acc: 0.375, loss: 1.122
epoch: 1400, acc: 0.375, loss: 1.114
epoch: 1500, acc: 0.375, loss: 1.107
epoch: 1600, acc: 0.375, loss: 1.102
epoch: 1700, acc: 0.438, loss: 1.097
epoch: 1800, acc: 0.438, loss: 1.091
epoch: 1900, acc: 0.438, loss: 1.086
epoch: 2000, acc: 0.438, loss: 1.080
epoch: 2100, acc: 0.562, loss: 1.074
epoch: 2200, acc: 0.562, loss: 1.067
epoch: 2300, acc: 0.562, loss: 1.060
epoch: 2400, acc: 0.562, loss: 1.051
epoch: 2500, acc: 0.500, loss: 1.041
epoch: 2600, acc: 0.500, loss: 1.030
epoch: 2700, acc: 0.500, loss: 1.017
epoch: 2800, acc: 0.562, loss: 1.004
epoch: 2900, acc: 0.562, loss: 0.989
epoch: 3000, acc: 0.562, loss: 0.973
epoch: 3100, acc: 0.562, loss: 0.957
epoch: 3200, acc: 0.562, loss: 0.940
epoch: 3300, acc: 0.562, loss: 0.922
epoch: 3400, acc: 0.562, loss: 0.905
epoch: 3500, acc: 0.562, loss: 0.888
epoch: 3600, acc: 0.562, loss: 0.872
epoch: 3700, acc: 0.562, loss: 0.855
epoch: 3800, acc: 0.562, loss: 0.840
epoch: 3900, acc: 0.562, loss: 0.825
epoch: 4000, acc: 0.625, loss: 0.810
epoch: 4100, acc: 0.625, loss: 0.796
epoch: 4200, acc: 0.625, loss: 0.782
epoch: 4300, acc: 0.625, loss: 0.768
epoch: 4400, acc: 0.625, loss: 0.755
epoch: 4500, acc: 0.625, loss: 0.742
epoch: 4600, acc: 0.688, loss: 0.728
epoch: 4700, acc: 0.688, loss: 0.715
epoch: 4800, acc: 0.688, loss: 0.702
epoch: 4900, acc: 0.750, loss: 0.689
epoch: 5000, acc: 0.750, loss: 0.676
epoch: 5100, acc: 0.750, loss: 0.663
epoch: 5200, acc: 0.812, loss: 0.649
epoch: 5300, acc: 0.812, loss: 0.636
epoch: 5400, acc: 0.812, loss: 0.622
epoch: 5500, acc: 0.812, loss: 0.608
epoch: 5600, acc: 0.812, loss: 0.594
epoch: 5700, acc: 0.812, loss: 0.580
epoch: 5800, acc: 0.812, loss: 0.566
epoch: 5900, acc: 0.812, loss: 0.551
epoch: 6000, acc: 0.812, loss: 0.537
epoch: 6100, acc: 0.812, loss: 0.522
epoch: 6200, acc: 0.875, loss: 0.507
epoch: 6300, acc: 0.875, loss: 0.492
epoch: 6400, acc: 0.875, loss: 0.478
epoch: 6500, acc: 0.875, loss: 0.463
epoch: 6600, acc: 0.938, loss: 0.449
epoch: 6700, acc: 0.938, loss: 0.434
epoch: 6800, acc: 0.938, loss: 0.420
epoch: 6900, acc: 0.938, loss: 0.406
epoch: 7000, acc: 0.938, loss: 0.392
epoch: 7100, acc: 0.938, loss: 0.379
epoch: 7200, acc: 0.938, loss: 0.366
epoch: 7300, acc: 0.938, loss: 0.353
epoch: 7400, acc: 0.938, loss: 0.340
epoch: 7500, acc: 0.938, loss: 0.328
epoch: 7600, acc: 0.938, loss: 0.316
epoch: 7700, acc: 0.938, loss: 0.305
epoch: 7800, acc: 1.000, loss: 0.294
epoch: 7900, acc: 1.000, loss: 0.283
epoch: 8000, acc: 1.000, loss: 0.273
epoch: 8100, acc: 1.000, loss: 0.263
epoch: 8200, acc: 1.000, loss: 0.254
epoch: 8300, acc: 1.000, loss: 0.245
epoch: 8400, acc: 1.000, loss: 0.236
epoch: 8500, acc: 1.000, loss: 0.227
epoch: 8600, acc: 1.000, loss: 0.219
epoch: 8700, acc: 1.000, loss: 0.211
epoch: 8800, acc: 1.000, loss: 0.204
epoch: 8900, acc: 1.000, loss: 0.197
epoch: 9000, acc: 1.000, loss: 0.190
epoch: 9100, acc: 1.000, loss: 0.183
epoch: 9200, acc: 1.000, loss: 0.177
epoch: 9300, acc: 1.000, loss: 0.170
epoch: 9400, acc: 1.000, loss: 0.164
epoch: 9500, acc: 1.000, loss: 0.159
epoch: 9600, acc: 1.000, loss: 0.153
epoch: 9700, acc: 1.000, loss: 0.148
epoch: 9800, acc: 1.000, loss: 0.143
epoch: 9900, acc: 1.000, loss: 0.138

In [ ]:
Y_train

array([[1, 1, 0, ..., 0, 1, 2],
       [2, 2, 1, ..., 0, 1, 1],
       [0, 0, 1, ..., 1, 1, 0],
       ...,
       [2, 0, 1, ..., 1, 0, 0],
       [2, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 2, 2, 2]])

In [ ]:
print(Y_train_one_hot.shape)

(100, 16, 3)

In [ ]:
# Problema com overfitting

In [ ]:
# Plotar gráficos usando o dataframe