In [52]:
import polars as pl
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [53]:
df = pl.read_csv('data_neural_network.csv')
#df

In [54]:
# Excluir a coluna density que não está normalizada
df = df.drop('density')
# Conversão de strings para números
mapper = {
    'Photon':-1,
    'Proton':float(np.log(1)),
    'Iron':float(np.log(56))
}

trigs = []
for i in range(1,101):
    trig = 'TRIG' + str(i)
    trigs.append(trig)

trigs = dict((list(enumerate(trigs, 1))))

trigs = {value: key for key, value in trigs.items()}

df = df.with_columns(
    pl.col('composition').map_dict(mapper, default=None),
    pl.col('TRIG').map_dict(trigs, default=None)
    )

In [55]:
df

shape: (2_000, 4)
┌──────┬─────────────┬───────────┬────────────────────┐
│ TRIG ┆ composition ┆ energy    ┆ density_normalized │
│ ---  ┆ ---         ┆ ---       ┆ ---                │
│ i64  ┆ f64         ┆ f64       ┆ f64                │
╞══════╪═════════════╪═══════════╪════════════════════╡
│ 65   ┆ -1.0        ┆ 1.0000e14 ┆ 0.001325           │
│ 29   ┆ 0.0         ┆ 2.1500e15 ┆ 0.014233           │
│ 54   ┆ 4.025352    ┆ 4.6400e15 ┆ 0.076239           │
│ 27   ┆ 4.025352    ┆ 1.0000e14 ┆ 0.000189           │
│ …    ┆ …           ┆ …         ┆ …                  │
│ 27   ┆ 0.0         ┆ 4.6400e15 ┆ 0.084529           │
│ 2    ┆ 0.0         ┆ 2.1500e14 ┆ 0.000568           │
│ 11   ┆ 0.0         ┆ 4.6400e14 ┆ 0.000946           │
│ 90   ┆ 0.0         ┆ 2.1500e15 ┆ 0.008214           │
└──────┴─────────────┴───────────┴────────────────────┘

In [58]:
df_filtered = df.filter(pl.col("TRIG") == 24)
df_filtered

shape: (20, 4)
┌──────┬─────────────┬───────────┬────────────────────┐
│ TRIG ┆ composition ┆ energy    ┆ density_normalized │
│ ---  ┆ ---         ┆ ---       ┆ ---                │
│ i64  ┆ f64         ┆ f64       ┆ f64                │
╞══════╪═════════════╪═══════════╪════════════════════╡
│ 24   ┆ 4.025352    ┆ 2.1500e14 ┆ 0.000303           │
│ 24   ┆ -1.0        ┆ 4.6400e14 ┆ 0.004845           │
│ 24   ┆ -1.0        ┆ 1.0000e13 ┆ 0.0                │
│ 24   ┆ 0.0         ┆ 1.0000e14 ┆ 0.00053            │
│ …    ┆ …           ┆ …         ┆ …                  │
│ 24   ┆ 0.0         ┆ 1.0000e15 ┆ 0.015445           │
│ 24   ┆ -1.0        ┆ 1.0000e14 ┆ 0.000379           │
│ 24   ┆ 0.0         ┆ 1.0000e13 ┆ 0.000151           │
│ 24   ┆ 0.0         ┆ 2.1500e15 ┆ 0.033615           │
└──────┴─────────────┴───────────┴────────────────────┘

In [88]:
df_neural = df.group_by('TRIG').agg(pl.col("density_normalized","composition", "energy"))
df_neural = df_neural.with_columns(pl.col('TRIG').cast(pl.Utf8))
df_neural = df_neural.transpose(column_names= 'TRIG')

In [92]:
df_neural

shape: (3, 100)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ 24        ┆ 40        ┆ 96        ┆ 72        ┆ … ┆ 87        ┆ 55        ┆ 39        ┆ 79       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ list[f64] ┆ list[f64] ┆ list[f64] ┆ list[f64] ┆   ┆ list[f64] ┆ list[f64] ┆ list[f64] ┆ list[f64 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ [0.000303 ┆ [0.000114 ┆ [0.006435 ┆ [0.000076 ┆ … ┆ [0.0,     ┆ [0.314873 ┆ [0.007874 ┆ [0.00037 │
│ ,         ┆ ,         ┆ ,         ┆ ,         ┆   ┆ 0.024681, ┆ ,         ┆ ,         ┆ 9, 0.000 │
│ 0.004845, ┆ 0.015975, ┆ 0.00053,  ┆ 0.000303, ┆   ┆ …         ┆ 0.032063, ┆ 0.072264, ┆ 416, …   │
│ …         ┆ …         ┆ …         ┆ …         ┆   ┆ 0.000114] ┆ …         ┆ …         ┆ 0.000833 │
│ 0.033615] ┆ 0.000719] ┆ 0.035242] ┆ 0.001628] ┆   ┆           ┆ 0.184465] ┆ 0.017867] ┆ ]        │
│ [4.025352 ┆ [-1.0,    ┆ [-1.0,    ┆ [4.025352 ┆ … ┆ [-1.0,    ┆ [-1.0,    ┆ [-1.0,    ┆ [-1.0,   │
│ , -1.0, … ┆ -1.0, …   ┆ 4.025352, ┆ , 0.0, …  ┆   ┆ -1.0, …   ┆ -1.0, …   ┆ -1.0, …   ┆ 0.0, …   │
│ 0.0]      ┆ -1.0]     ┆ … 0.0]    ┆ 4.025352] ┆   ┆ 4.025352] ┆ 4.025352] ┆ 4.025352] ┆ 0.0]     │
│ [2.1500e1 ┆ [1.0000e1 ┆ [1.0000e1 ┆ [2.1500e1 ┆ … ┆ [1.0000e1 ┆ [2.1500e1 ┆ [1.0000e1 ┆ [1.0000e │
│ 4, 4.6400 ┆ 4, 2.1500 ┆ 5, 4.6400 ┆ 4, 1.0000 ┆   ┆ 3, 2.1500 ┆ 5, 4.6400 ┆ 5, 4.6400 ┆ 14, 1.00 │
│ e14, …    ┆ e15, …    ┆ e14, …    ┆ e14, …    ┆   ┆ e15, …    ┆ e14, …    ┆ e15, …    ┆ 00e14, … │
│ 2.1500e…  ┆ 2.1500e…  ┆ 4.6400e…  ┆ 1.0000e…  ┆   ┆ 2.1500e…  ┆ 4.6400e…  ┆ 4.6400e…  ┆ 2.1500e… │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [99]:
# Se eu quiser mostrar qual tanque a lista se refere, devo usar o parâmetro named = True
#density = df_neural.row(0, named= True)
density = df_neural.row(0)
composition = df_neural.row(1)
energy = df_neural.row(2)

In [5]:
# Separação dos dados, vamos descobrir somente a composição

X_comp = df.drop('composition','energy')
Y_comp = df.drop('TRIG', 'density_normalized', 'energy')

X_comp = X_comp.to_numpy()
Y_comp = Y_comp.to_numpy()

# Separação dos dados de teste e treino

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X_comp, Y_comp, test_size= 0.2)

Vamos usar a arquitetura Feed-Forward Network pois teremos camadas sucessivas que alimentam as próximas - começando na camada de entrada e terminando na camada de saída. Todos os nós da rede estão conectados aos da próxima camada. 

Para um vetor *z* de dimensão *K* classes, temos que a função softmax é definida como
$$softmax(z_i) = \frac{exp(z_i)}{\sum_{j = 1}^{K} exp(z_j)}, 1 \leq i \leq K$$ 

Ainda, temos que o vetor *z* é definido por

$$z = \left(\sum_{i = 1}^{n}w_ix_i\right) + b $$

onde, $x_i$ são as entradas, $w_i$ são os pesos e *b* é o bias (viés). Sendo assim, a função softmax transforma o vetor *z* em probabilidades entre 0 e 1.

Para treinar o modelo, vamos utilizar a **Função de perda de Entropia Cruzada (Cross-Entropy Loss)**. A distância entre a saída do modelo e a saída real é chamada de função de perda ou de custo. E portanto, temos que minimizar essa distância, ou seja, essa perda, ao máximo para que o modelo tenha resultados melhores. Na forma matemática, estaremos calculando os pesos $w_i$ e o bias *b* com a função de perda e depois otimizando esses valores minimizandos-os com o **Gradiente Descendente Estocástico.**

In [6]:
# Arquitetura que será usada: feed-forward network
# Qual será o tamanho da rede neural? Digo, tamanho de cada camada. 
# Quais pesos vou inicializar?
# Qual função de ativação vou usar? Deve ser não linear Softmax
# Como minimizar os pesos? Função de Perda deve ser diferenciável, isso implica que a função de ativação também deve ser diferenciável.
# Gradiente descendente
# Backpropagation

In [7]:
class NeuralNetwork:
    def __init__(self, n_inputs, n_neurons):
    # Inicialização dos pesos e bias
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
    # Calcula os valores de saída de cada camada
        self.inputs = inputs
        self.output = np.dot(inputs, self.weights) + self.biases # X.W + b

    def backward(self, dvalues):
        # Gradiente dos parâmetros
        self.dweights = np.dot(self.inputs.T, dvalues)
        self.dbiases = np.sum(dvalues, axis = 0, keepdims = True)
        # Gradiente dos valores
        self.dinputs = np.dot(dvalues, self.weights.T)

In [8]:
class ReLU():
    def forward(self, inputs):
        self.inputs = inputs
        self.output = np.maximum(0, inputs) # Função ReLU R(x) = max(0,x)
    def backward(self,dvalues):
        self.dinputs = dvalues.copy()
        self.dinputs[self.inputs <= 0] = 0

In [9]:
class Softmax():
    def forward(self,inputs):
        # Probabilidades não normalizadas
        exp_values = np.exp(inputs - np.max(inputs, axis = 1, keepdims = True))
        # Normalização
        probabilities = exp_values / np.sum(exp_values, axis = 1, keepdims = True)
        self.output = probabilities

In [10]:
class Loss:
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss

In [11]:
class LossCategoricalCrossentropy(Loss):
    # Forward pass
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)

        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[
                range(samples),
                y_true
            ]

        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(
                y_pred_clipped * y_true,
                axis=1
            )

        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods


    def backward(self, dvalues, y_true):

        samples = len(dvalues)
        labels = len(dvalues[0])

        if len(y_true.shape) == 1:
            y_true = np.eye(labels)[y_true]

        # Gradiente
        self.dinputs = -y_true / dvalues
        # Normalização
        self.dinputs = self.dinputs / samples

In [12]:
class Activation_Softmax_Loss_CategoricalCrossentropy:
    
    def __init__(self):
        self.activation = Softmax()
        self.loss = LossCategoricalCrossentropy()

    def forward(self, inputs, y_true):
        self.activation.forward(inputs)
        self.output = self.activation.output
        return self.loss.calculate(self.output, y_true)

    def backward(self, dvalues, y_true):
        samples = len(dvalues)

        if len(y_true.shape) == 2:
            y_true = np.argmax(y_true, axis=1)

        self.dinputs = dvalues.copy()
        # Gradiente
        self.dinputs[range(samples), y_true] -= 1
        # Normalização
        self.dinputs = self.dinputs / samples

In [13]:
# Gradiente Descendente 
class Optimizer_GD:
 
 def __init__(self, learning_rate=0.01):
  self.learning_rate = learning_rate

 def update_params(self, layer):
  layer.weights += -self.learning_rate * layer.dweights
  layer.biases += -self.learning_rate * layer.dbiases

In [18]:
# Cria a primeira camada, sendo 2 de entrada e 32 de saída
layer1 = NeuralNetwork(2, 32)

# Cria a função de ativação ReLU
activation1 = ReLU()

# Cria uma segunda camada que tem 6 valores de saída
layer2 = NeuralNetwork(32, 3)

# Cria a função perda e softmax
loss_activation = Activation_Softmax_Loss_CategoricalCrossentropy()

# Cria o gradiente descendente
optimizer = Optimizer_GD()

# Treinamento em loop
for epoch in range(500):
    # Com os dados de treino, aplicando o método forward
    layer1.forward(X_train)
    
    # Usa a função de ativação da saída da primeira camada
    activation1.forward(layer1.output)
    
    # Passe os resultados para a próxima camada
    layer2.forward(activation1.output)
    
    # Usa os dados da segunda camada para a função de perda e softmax
    loss = loss_activation.forward(layer2.output, Y_train)
    
    # Calcula a precisão
    predictions = np.argmax(loss_activation.output, axis=1)
    #if len(Y_train.shape) == 2:
    #    Y_train = np.argmax(Y_train, axis=1)
    accuracy = np.mean(predictions == Y_train)
    
    if not epoch % 100:
        print(f'epoch: {epoch}, ' +
              f'acc: {accuracy:.3f}, ' +
              f'loss: {loss:.3f}')
    
    # Backward
    loss_activation.backward(loss_activation.output, Y_train)
    layer2.backward(loss_activation.dinputs)
    activation1.backward(layer2.dinputs)
    layer1.backward(activation1.dinputs)
    
    # Atualiza o peso e bias para as camadas 1 e 2
    optimizer.update_params(layer1)
    optimizer.update_params(layer2)

epoch: 0, acc: 1.000, loss: 1.097
epoch: 100, acc: 1.000, loss: 0.045
epoch: 200, acc: 1.000, loss: 0.030
epoch: 300, acc: 1.000, loss: 0.023
epoch: 400, acc: 1.000, loss: 0.019

In [16]:
# Problema com overfitting

In [17]:
# Plotar gráficos usando o dataframe